services:
  nginx:
    image: nginx:alpine
    ports:
      - "90:90"  # Map host port 80 to container port 80
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./database:/var/www/database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge